// app/layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import { MantineProvider } from '@mantine/core';
import { AuthProvider } from './context/AuthContext';
import FCMHandler from '@/components/fcm-handler';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <AuthProvider>
          <FCMHandler />
          <Toaster />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}